### PR TITLE
Remove Muzzle

### PR DESCRIPTION
**Pull request by RobLoach**
Doesn't use raylib anymore.

### CODE REVIEW

**Comment by Rabios** [comment]
@RobLoach Done, Thanks so much! ❤️

**Comment by OkiStuff** [comment]
Lol, I was just looking to see if Muzzle was still on this list to remove it. Good catch!

**Comment by RicoP** [comment]
When I look at the Muzzle header it looks like it still provides a #ifdef for raylib, so i am not sure if this is 100% true that Muzzle isn't using raylib anymore

https://github.com/PikoStudios/Muzzle/blob/main/include/MuzzleGL.h

**Comment by OkiStuff** [comment]
That was for RLGL. that file has been removed in another branch (I'm the maintainer of muzzle)

**Pull request merged**
